name: ESlint

on:
  push:
    paths:
      - 'functions/**'
      - 'tests/**'
  
  pull_request:
    paths:
      - 'functions/**'
      - 'tests/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run lint